### ISSUE TITLE
Build doesn't fail on massive coverage drop

### ISSUE THREAD

**Issue by beatngu13** [retest/recheck#186]
#154 accidentially removed the JUnit 4 dependency. As a result, hundreds of tests haven't been executed anymore, which resulted in a massive coverage drop from ~55% (PR before: https://github.com/retest/recheck/runs/79978478) to ~37% (PR after: https://github.com/retest/recheck/runs/84153719).

Our [SonarCloud Quality Gate](https://sonarcloud.io/organizations/retest/quality_gates/show/860) should cause an error when the overall coverage is less than 40%, but it didn't. We have to further investigate this to avoid similar issues in the future. (For testing, one can remove the JUnit 4 dependency again and see what SonarCloud does.)

**Comment by diba1013** [comment]
We will track this internally if this happens again.
