### ISSUE TITLE
Instead of ignore, give general rules

### ISSUE THREAD

**Issue by roesslerj** [retest/recheck#28]
Instead of ignoring current date or build number, have a rule that specifies e.g. `currentDate` or `matches(\d\.\d\.\d\d)`. This is better than ignoring...

Question: Could be achieved with regular `asserts` also. Does it make sense, to add that functionality to recheck?

**Comment by beatngu13** [comment]
Do we have addressed this with our `recheck.ignore` matcher mechanism?

**Comment by roesslerj** [comment]
No. In my intuition, this would be e.g. something like 
`<attribute key="text" xsi:type="textAttribute">${some scripting language expression}</attribute>`.

**Comment by diba1013** [comment]
We will track this internally.
