### ISSUE TITLE
RecheckOptions should reuse given FileNamerStrategy

### ISSUE THREAD

**Issue by beatngu13** [retest/recheck#312]
We currently use Lombok to create a builder for our `RecheckOptions`:

```java
@SuperBuilder
@Getter
public class RecheckOptions {

	@Builder.Default
	private final FileNamerStrategy fileNamerStrategy = new MavenConformFileNamerStrategy();

	@Builder.Default
	private final String suiteName = new MavenConformFileNamerStrategy().getTestClassName();

	@Builder.Default
	private final boolean rehubEnabled = false;

}
```

This is all fine until a user has to provide a custom `FileNamerStrategy` if, for instance, we cannot determine the test class/method name in the call stack (see e.g. #301 and https://github.com/retest/recheck-web/issues/268).

The key point here is that if the user passes a `FileNamerStrategy`, we should reuse it in `suiteName`. Otherwise, one has to do:

```java
RecheckOptions.builder()
		.fileNamerStrategy( fileNamerStrategy )
		.suiteName( fileNamerStrategy.getTestClassName() )
		.build()
```

Which is somewhat redudant. I would expect the following default(s):

```java
@Builder.Default
private final FileNamerStrategy fileNamerStrategy = new MavenConformFileNamerStrategy();

@Builder.Default
private final String suiteName = fileNamerStrategy.getTestClassName();
```

But that's not possible with Lombok's builder.

Consequently, I would suggest to [delombok](https://projectlombok.org/features/delombok) `RecheckOptions` and reimplement a simplified version without Lombok, which addresses this issue but is still compatible and extensible.

**Comment by martin-v** [comment]
Better option to implement the complete builder is to overwrite the `getSuiteName()`.
