### ISSUE TITLE
Wrong report version

### ISSUE THREAD

**Issue by javydreamercsw** [retest/recheck#315]
The report generated with Recheck using the following pom:
`
        <dependency>
            <groupId>de.retest</groupId>
            <artifactId>recheck-web</artifactId>
            <version>1.1.0</version>
        </dependency>
`
Which pulls recheck 1.1.1.

The report generated has reTestVersion="1.2.0" making the CLI fail with: 
`The report was created with another, incompatible recheck version.
Please, use the same recheck version to load a report with which it was generated.`

**Comment by beatngu13** [comment]
Could you please show me a) the complete POM and b) the output of `recheck version`? Usually recheck, recheck-web, recheck.cli (or review) should be compatible when used with the same major and minor version.

**Comment by javydreamercsw** [comment]
`recheck version
recheck CLI version 1.1.0
Java version 1.8.0_151
`
pom:
`<dependencies>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.2.3</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
      <version>5.1.5.RELEASE</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
      <version>2.9.9</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.saucelabs</groupId>
      <artifactId>sauce_junit</artifactId>
      <version>2.1.25</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.sun.mail</groupId>
      <artifactId>javax.mail</artifactId>
      <version>1.6.2</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jsoup</groupId>
      <artifactId>jsoup</artifactId>
      <version>1.11.3</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.appium</groupId>
      <artifactId>java-client</artifactId>
      <version>7.0.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-remote-driver</artifactId>
      <version>3.141.59</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.github.webdriverextensions</groupId>
      <artifactId>webdriverextensions</artifactId>
      <version>3.11.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.github.bonigarcia</groupId>
      <artifactId>webdrivermanager</artifactId>
      <version>3.6.1</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.security.oauth</groupId>
      <artifactId>spring-security-oauth2</artifactId>
      <version>2.3.3.RELEASE</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>2.9.9</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.9.9</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>commons-lang</groupId>
      <artifactId>commons-lang</artifactId>
      <version>2.6</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testng</groupId>
      <artifactId>testng</artifactId>
      <version>6.14.3</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.atlassian.jira</groupId>
      <artifactId>jira-rest-java-client-core</artifactId>
      <version>5.0.4</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.atlassian.fugue</groupId>
      <artifactId>fugue</artifactId>
      <version>2.7.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.aeonbits.owner</groupId>
      <artifactId>owner</artifactId>
      <version>1.0.10</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>net.javacrumbs.json-unit</groupId>
      <artifactId>json-unit-assertj</artifactId>
      <version>2.7.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.8</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>de.retest</groupId>
      <artifactId>recheck-web</artifactId>
      <version>1.1.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>de.retest</groupId>
      <artifactId>recheck</artifactId>
      <version>1.2.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.google.inject</groupId>
      <artifactId>guice</artifactId>
      <version>4.2.2</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>`

I tried overwriting the inherited recheck version without success.

**Comment by javydreamercsw** [comment]
I assume the dependencies is enough.Lots of internal stuff in the rest of the POM.

**Comment by beatngu13** [comment]
Yep, that's fine—thanks!

There is no need to explicitly depend on recheck when you already have recheck-web, which should pull it's own (compatible) version of it.

Have you tried removing recheck from the POM? [recheck-web 1.1.0](https://github.com/retest/recheck-web/blob/v1.1.0/pom.xml#L81) should depend on recheck 1.1.1, which is also used by [recheck.cli 1.1.0](https://github.com/retest/recheck.cli/blob/v1.1.0/pom.xml#L80).

**Comment by javydreamercsw** [comment]
That's how I tried initially but the report shows version 1.2.0.

**Comment by beatngu13** [comment]
When you say the report shows version 1.2.0, where do you get this version/information from? Unfortunately, I cannot reproduce the error locally. When I create a report with recheck-web 1.1.0, I can open it with recheck.cli 1.1.0.

**Comment by javydreamercsw** [comment]
I refer to the xml file it creates.

**Comment by javydreamercsw** [comment]
I'll try to b update the sample project and see.

**Comment by beatngu13** [comment]
Are you trying to open the XML? Those are the state, respectively, Golden Master files. With the recheck.cli, you are supposed to open reports (`.report` extension). For instance:

```
$ recheck diff my.package.MyTest.report
```

**Comment by javydreamercsw** [comment]
That's the file Im trying to open. We'll applicable for my case.

**Comment by beatngu13** [comment]
Sorry, but based on this information I cannot reproduce the issue.

**Comment by javydreamercsw** [comment]
Worked fine. I guess I was trying to open the wrong file.
