### ISSUE TITLE
RGB differences are not updated in the recheck.ignore file

### ISSUE THREAD

**Issue by javydreamercsw** [retest/recheck#446]
Testing recheck web 1.5.1 with Review 1.5.0 (since there seems not to be a 1.5.1) I get some differences on the report:
![Screen Shot 2019-09-27 at 3 08 40 PM](https://user-images.githubusercontent.com/2817343/65799012-b6096d00-e138-11e9-813f-476b16c47a81.png)

![Screen Shot 2019-09-27 at 3 09 10 PM](https://user-images.githubusercontent.com/2817343/65799073-df29fd80-e138-11e9-8e01-fa9471654bd3.png)

![Screen Shot 2019-09-27 at 3 09 22 PM](https://user-images.githubusercontent.com/2817343/65799081-e224ee00-e138-11e9-9d60-9c6abde0a7a1.png)

The changes are applied but no actual changes make it to the recheck.ignore file.

I wouldn't be surprised it's related to the check/test name containing spaces.

**Comment by beatngu13** [comment]
I assume the file `Middle Initial Input` was updated properly? The message that the `recheck.ignore` has been updated always pops up at the moment, that's an issue in review. CC @diba1013

**Comment by javydreamercsw** [comment]
Yes, it was.

**Comment by javydreamercsw** [comment]
I was trying to find a way to ignore RGB changes but can't figure out a way.

**Comment by beatngu13** [comment]
Instead of using the check boxes for accepting the changes (under "Accept all"), have you tried ignoring them (under "Ignore all")? This should also update the ignore file.

Alternatively, if you want to ignore these changes for all elements, you can add the following to your `recheck.ignore`:

```
attribute=border-top-color
attribute=border-bottom-color
attribute=border-left-color
attribute=border-right-color
```

Or with a regex:

**EDIT:** Fixed ignore (`=` instead of `:`) …

```
attribute-regex=border-.*-color
```

Does this help? You can also find more information here:

https://docs.retest.de/recheck/how-ignore-works/

**Comment by diba1013** [comment]
@beatngu13 is correct.

1. The `recheck.ignore` is saved every time, since we do not track the modifications done by the user (i.e. a `dirty`-flag).
2. In the screenshot you selected "Accept" for the border*colors. Keep in mind that " Accept" will update the Golden Master (i.e. save them) while "Ignore" will update the ´recheck.ignore`. Thus to ignore the colors, you will want to select "Ignore".
3. > I was trying to find a way to ignore RGB changes but can't figure out a way.

    It is currently only possible to ignore attributes (with their respective key: e.g. `attribute-regex: border-.*-color`), but not their actual values (e.g. `rgb(${r}, ${g}, ${b})`). If step 2. does not work, you have to update the `recheck.ignore` file manually (like @beatngu13 suggested above).

**Comment by javydreamercsw** [comment]
I tried `attribute-regex: border-.*-color` but still got the failure due to differences.

```
Test 'Add User' has 12 difference(s) in 7 state(s):
Middle Initial Input resulted in:
	input at 'html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/span[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/label[3]/span[2]/input[1]':
		border-bottom-color: expected="rgb(186, 220, 235)", actual="rgb(191, 222, 236)"
		border-left-color: expected="rgb(186, 220, 235)", actual="rgb(191, 222, 236)"
		border-right-color: expected="rgb(186, 220, 235)", actual="rgb(191, 222, 236)"
		border-top-color: expected="rgb(186, 220, 235)", actual="rgb(191, 222, 236)"
Last Name Input resulted in:
	input at 'html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/span[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/label[4]/span[2]/input[1]':
		border-bottom-color: expected="rgb(67, 163, 210)", actual="rgb(79, 168, 212)"
		border-left-color: expected="rgb(67, 163, 210)", actual="rgb(79, 168, 212)"
		border-right-color: expected="rgb(67, 163, 210)", actual="rgb(79, 168, 212)"
		border-top-color: expected="rgb(67, 163, 210)", actual="rgb(79, 168, 212)"
Prefix Input resulted in:
	input at 'html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/span[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/label[1]/span[2]/input[1]':
		border-bottom-color: expected="rgb(118, 187, 221)", actual="rgb(111, 184, 219)"
		border-left-color: expected="rgb(118, 187, 221)", actual="rgb(111, 184, 219)"
		border-right-color: expected="rgb(118, 187, 221)", actual="rgb(111, 184, 219)"
		border-top-color: expected="rgb(118, 187, 221)", actual="rgb(111, 184, 219)"
```

**Comment by diba1013** [comment]
Oh, sorry, that is my bad. It is actually:
```
attribute-regex=border-.*-color
```
With an equal `=` sign and no spaces. 

Unfortunately our syntax for the filters is quite strict and not well/wrong documented. I already proposed an updated documentation which is currently in review: retest/docs#51.

**Comment by javydreamercsw** [comment]
That did the trick, thanks!
