### ISSUE TITLE
Integrate into JUnit for life-cycle management

### ISSUE THREAD

**Issue by roesslerj** [retest/recheck#448]
Use JUnit 5 and JUnit 4 to get rid of necessary explicit calls to `capTest()` and `cap()`.

**Comment by diba1013** [comment]
Could you elaborate this a bit? Please, specify your concrete problem and your proposal for a solution.

**Comment by beatngu13** [comment]
I assume:

* https://github.com/retest/recheck-junit-4-extension
* https://github.com/retest/recheck-junit-jupiter-extension

?

**Comment by roesslerj** [comment]
Yes. This is not yet productively usable, and this issue tracks the progress and current status.

**Comment by diba1013** [comment]
We released 1.6.0 releases for the above mentioned extensions.
