### ISSUE TITLE
Better error message when cap() is uses instead of capTest()

### ISSUE THREAD

**Issue by beatngu13** [retest/recheck#58]
If someone accidentially uses `cap()` instead of `capTest()` within a test, like so:

```java
@Test
void someTest() throws Exception {
   re.startTest();

   // ...

   re.cap(); // instead of re.capTest()
}
```

Then a `NullPointerException` is thrown. Here, a better error message would be very helpful.

**Comment by kema91** [comment]
Issue is obsolete, `cap()` calls `capTest()` and display a warning message.
